# -*- coding: utf-8 -*-
"""Gen AI lab-05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoP9Swm-MAndyXk_5gnchU4vmY7IPa56
"""

!pip install diffusers transformers accelerate

# 1) Load a Transformer-based T2I model (PixArt-a / DiT)

model_id = "PixArt-alpha/PixArt-XL-2-512x512"

import torch
from diffusers import PixArtAlphaPipeline

dtype = torch.float16 if torch.cuda.is_available() else torch.float32

pipe = PixArtAlphaPipeline.from_pretrained(
    model_id,
    torch_dtype=dtype,
)

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe.to(device)

# Optional: enable faster attention if available
if device == "cuda":
    pipe.enable_model_cpu_offload()
    # works well on limited VRAM
    pipe.enable_vae_slicing()

#2) Write a good prompt for a face

prompt = (
"Ultra-realistic close-up portrait of a young adult human, neutral expression,"
)

negative_prompt = (
"blurry, low quality, extra fingers, extra eyes, deformed, text, watermark, logo"
)

#3) Generate the image

generator = torch.Generator(device=device).manual_seed(42) # set seed for reproducibility

image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=24, # increase for slightly higher quality
    guidance_scale=4.5, # 3.5-6 is typical
    height=512,
    width=512,
    generator=generator
).images[0]

#4) Save the result

image.save("face.png")

print("Saved to face.png")

from IPython.display import Image
display(Image(filename='face.png'))