# -*- coding: utf-8 -*-
"""Gen AI lab - 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjQBBRvzdu41MaKULpRq9zcK6NPzCADv
"""

! pip install gradio

import gradio as gr

def greet(name):
   return f"Hello welcome, {name}!"

demo = gr.Interface(fn=greet, inputs=gr.Textbox(label="Enter Your name"), outputs=gr.Text(label="Greeting"))

demo.launch(share=False)

import gradio as gr

def multiply_by_slider(value):
    return value * 2

demo = gr.Interface(fn=multiply_by_slider, inputs=gr.Slider(1, 100, label="Select a value"), outputs=gr.Number(label="Result"))
demo.launch(share=False)

import gradio as gr

def check(value):
    return "Checked" if value else "Not Checked"

demo = gr.Interface(fn=check, inputs=gr.Checkbox(label="Check me"), outputs=gr.Text(label="Status"))
demo.launch(share=False)

import gradio as gr

def select_option(option):
    return f"You selected: {option}"

demo = gr.Interface(fn=select_option, inputs=gr.Radio(["Option 1", "Option 2"], label="Pick an option"), outputs=gr.Text(label="Selected Option"))
demo.launch(share=False)