# -*- coding: utf-8 -*-
"""gen AI  lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN5GL3MAWwJKoKglE92Ac_0WHn-2looy
"""

from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")
text = "I am feeling happy"
sentiment_result = sentiment_analyzer(text)
print("Sentiment analysis:")
print(f"Sentiment: {sentiment_result[0]['label']} (score: {sentiment_result[0]['score']:.2f})\n")

from transformers import pipeline
translator_en_to_fr = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
text = "I am feeling happy"
translation_result = translator_en_to_fr(text)
print("Translation:")
print(f"Translated text: {translation_result[0]['translation_text']}\n")

!pip install pytesseract

import pytesseract
from PIL import Image
from transformers import pipeline

from PIL import Image

# Load the image
input_image = Image.open('/content/OIP.jpg')

# Display the image
display(input_image)

input_image.show()
from IPython.display import display
display(input_image)

!pip install pytesseract
import pytesseract
from PIL import Image
import re

input_image = Image.open('/content/OIP.jpg')

text_output = pytesseract.image_to_string(input_image, lang='eng').strip()

text_output = re.sub(r"\s+,", ",", text_output)

print(text_output)

