# -*- coding: utf-8 -*-
"""gen AI ex no-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKrJMft3ODojbFKQsCZpe_ups7pnzp0w
"""

from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")
text ="I am feeling happy"
sentiment_result = sentiment_analyzer(text)
print("Sentiment Analysis :")
print(f"Input : {text}")
print(f"Sentiment : {sentiment_result[0]['label']}(score: {sentiment_result[0]['score']:.2f})\n")

translator_en_to_fr = pipeline("translation_en_to_fr")
text = "I am feeling happy"
translation_result = translator_en_to_fr(text)

translator_en_to_fr = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
text = "I am feeling happy"
translation_result = translator_en_to_fr(text)
print("Translation :")
print(f"Input : {text}")
print(f"Translation : {translation_result[0]['translation_text']}\n")